name: 启动

on:
  schedule:
    - cron: '0 0/4 * * *'
        
jobs:
  start:
    runs-on: ubuntu-latest
    env:
      DEVICE_ID: ${{ secrets.DEVICE_ID }}
    steps:
      - uses: actions/checkout@v3
      - if: ${{ env.DEVICE_ID != '' }}
        name: 持续获取流量中...
        run: |
          python warp-plus.py
      - if: ${{ env.DEVICE_ID == '' }}
        name: 请先设置设备ID ！
