name: 测试

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: 获取IP
        run: curl -s ifconfig.me
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: 获取IP
        run: curl -s ifconfig.me
  job3:
    runs-on: ubuntu-latest
    steps:
      - name: 获取IP
        run: curl -s ifconfig.me
  job4:
    runs-on: ubuntu-latest
    steps:
      - name: 获取IP
        run: curl -s ifconfig.me
